/*
 * Copyright 2025 Red Hat, Inc. and/or its affiliates
 * and other contributors as indicated by the @author tags.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.keycloak.connections.redis;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.containsString;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.notNullValue;
import static org.hamcrest.Matchers.startsWith;

import org.junit.Test;

/**
 * Unit tests for TopologyInfo.
 * Tests topology information for multi-region deployments.
 *
 * @author Keycloak Redis Team
 */
public class TopologyInfoTest {

    @Test
    public void testCreate_WithNodeName() {
        // Given/When
        TopologyInfo info = new TopologyInfo("node-123", "us-east-1");

        // Then
        assertThat(info, notNullValue());
        assertThat(info.getMyNodeName(), equalTo("node-123"));
        assertThat(info.getMySiteName(), equalTo("us-east-1"));
    }

    @Test
    public void testCreate_WithAutoGeneratedNodeName() {
        // Given/When
        TopologyInfo info = new TopologyInfo();

        // Then
        assertThat(info, notNullValue());
        assertThat(info.getMyNodeName(), notNullValue());
        assertThat(info.getMyNodeName(), startsWith("node_"));
    }

    @Test
    public void testToString_FormatsCorrectly() {
        // Given
        TopologyInfo info = new TopologyInfo("node-1", "site-a");

        // When
        String output = info.toString();

        // Then
        assertThat(output, notNullValue());
        assertThat(output, containsString("node-1"));
        assertThat(output, containsString("site-a"));
    }
}
